name: ci
on: push
jobs:
  test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Switch Xcode to 12.4
        run: xcversion select 12.4
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v
